model_name: latent_diffusion_transformer
batch_size: 16
max_epoch: 100
learning_rate: 2.0e-05
max_grad_norm: 10
fp16: false
num_workers: 4
pin_memory: true
beta: 0.1
weights:
- 1
- 0.5
n_steps: 1000  # diffusion step
image_channels: 1
image_size_h: 128  # used in inference (not used in training) length?
image_size_w: 128  # used in inference (not used in training) pitches?
n_channels: 64
channel_multipliers:
- 1
- 2
- 2
- 4
is_attention:
- false
- false
- false
- true
vae:
  chpt: result/vae_0.1_0.0001/02-01_174905/chkpts/best_weights.pt
  chd_size: 256
  txt_size: 256
  num_channel: 10
  n_bars: 1
  is_sample: false
debug: true
